services:
  - type: web
    name: creator-profiler-api-plus-ai
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: PORT
        value: 10000
      - key: OPENAI_API_KEY
        sync: false
      - key: SERPAPI_KEY
        sync: false
      - key: YOUTUBE_API_KEY
        sync: false
  - type: web
    name: creator-profiler-dashboard
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run frontend/dashboard.py --server.address 0.0.0.0 --server.port $PORT
